config/routes.rb
Shopping::Application.routes.draw do
  get 'admin' => 'admin#index'
  get 'regist' => 'users#new'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users

  resources :orders

  resources :line_items

  resources :carts

  root :to=>'store#index' , :as=>'store'

  resources :products

end

app/models/user.rb
# encoding : UTF-8
require 'digest/sha2'
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation, :username, :birthday
  validates_uniqueness_of    :name , :message =>'登录名已经存在，请修改！'
  validates_presence_of       :name ,:message =>'登录名不能为空！'
  validates_presence_of       :username ,:message =>'用户名不能为空！'
  validates_presence_of       :birthday ,:message =>'出生日期不能为空！'
  validates  :password ,:confirmation=>true
  attr_accessor :password_confirmation
  attr_reader  :password
  validate :password_must_be_prensent

  def User.authenticate(name,password)
    if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password)
        user
      end
    end
  end
  def User.encrypt_password(password)
    Digest::SHA2.hexdigest(password)
  end

  def password=(password)
    @password = password
    if password.present?
      self.hashed_password = self.class.encrypt_password(password)
    end
  end

  private
  def password_must_be_prensent
    errors.add(:password ,'错误的密码！') unless hashed_password.present?
  end
  def genetate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end
end

app/controllers/users_controller.rb
#encoding : UTF-8
class UsersController < ApplicationController
  skip_before_filter :authorize, :only => [:new , :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url,
                                  notice: "新账户#{@user.name}创建成功！" }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url,
                                  notice: "#{@user.name}数据更新成功！" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2 style="text-align: center">有以下<%= pluralize(@user.errors.count,"项错误") %>，请检查！</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <table>
       <div class="span4">
          <tr>
            <td>登录账号：</td>
            <td><%= f.text_field :name %></td>
          </tr>
         <tr>
          <td>登录密码：</td>
          <td><%= f.password_field :password %></td>
        </tr>
          <tr>
            <td>确认密码：</td>
            <td><%= f.password_field :password_confirmation %></td>
          </tr>
          <tr>
            <td>真实姓名：</td>
            <td><%= f.text_field :username %></td>
          </tr>
          <tr>
            <td>出生日期：</td>
            <td><%= f.text_field :birthday %></td>
          </tr>
         <tr>
            <td style="text-align: right"><%= f.submit '注册', class:'btn btn-success' %></td>
            <td style="text-align: center"><%= link_to '返回' , store_url, class:'btn btn-primary' %></td>
         </tr>
       </div>
   </table>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h2>用户列表</h2>
<% if notice %>
    <p style="text-align: center"><%= notice %></p>
<% end %>

<table>
  <tr>
    <th>用户名</th>
    <th>登录名</th>
    <th>出生日期</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.name %></td>
    <td><%= user.birthday %></td>
    <td><%= link_to 'Show', user ,class:'btn btn-primary' %></td>
    <td><%= link_to 'Edit', edit_user_path(user) ,class:'btn btn-primary'%></td>
    <td><%= link_to 'Destroy', user, confirm: '确定删除么?', method: :delete, class:'btn btn-danger'%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path ,class:'btn btn-warning' %>

app/views/users/new.html.erb
<h3 style="text-align: center">新用户</h3>

<%= render 'form' %>

app/views/users/show.html.erb
<table>
<% if session[:user_id] %>
    <% user = User.find_by_id(session[:user_id]) %>
    <%= provide(:title,"#{user.username}___信息") %>
<% end %>

  <tr>
    <td>登录账号：</td>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <td>真实姓名：</td>
    <td><%= @user.username %></td>
  </tr>
  <tr>
    <td>出生日期：</td>
    <td><%= @user.birthday %></td>
  </tr>
</table>
<%= link_to '修改个人信息', edit_user_path(@user) %>